param()

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$dataDir = Join-Path $Root "data"
$jsonFile = Join-Path $dataDir "restream.json"
$confFile = Join-Path $dataDir "restream.conf"
$publicConfigFile = Join-Path $dataDir "public-config.json"
$publicHlsConf = Join-Path $dataDir "public-hls.conf"
$confCopy = Join-Path $Root "conf\data\restream.conf"
$defaultConfig = Join-Path $Root "config\restream.default.json"
$nginxExe = Join-Path $Root "nginx.exe"
$restart = ($env:RESTART_NGINX -eq "1")
$confBefore = if (Test-Path $confFile) { Get-Content $confFile -Raw } else { "" }
$publicHlsBefore = if (Test-Path $publicHlsConf) { Get-Content $publicHlsConf -Raw } else { "" }

function Clean-Value {
    param([string]$Value)
    if ($null -eq $Value) { return "" }
    $trimmed = $Value.Trim()
    if ($trimmed -match "[\r\n;]") { return $null }
    return $trimmed
}

function Build-PushUrl {
    param($Dest)
    $base = Clean-Value $Dest.rtmp_url
    if ($null -eq $base -or $base -eq "") { return $null }
    $key = Clean-Value $Dest.stream_key
    if ($null -eq $key) { return $null }
    if ($key) {
        $cleanKey = $key.TrimStart("/")
        if ($base.EndsWith("/")) { return $base + $cleanKey }
        return $base + "/" + $cleanKey
    }
    return $base
}

New-Item -ItemType Directory -Force -Path $dataDir | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $Root "conf\data") | Out-Null

if (!(Test-Path $jsonFile)) {
    Copy-Item $defaultConfig $jsonFile -Force
}

$data = Get-Content $jsonFile -Raw | ConvertFrom-Json
$lines = @(
    "# Auto-generated by restream-apply.ps1",
    "# Do not edit manually. Edit data/restream.json instead."
)

if ($data -and $data.destinations) {
    foreach ($dest in $data.destinations) {
        if (-not $dest.enabled) { continue }
        $pushUrl = Build-PushUrl $dest
        if ($pushUrl) { $lines += ("push " + $pushUrl + ";") }
    }
}

$lines -join "`n" | Out-File -FilePath $confFile -Encoding ASCII -Force
Copy-Item $confFile $confCopy -Force

$publicLive = $true
$publicHls = $true
if ($data.PSObject.Properties.Name -contains "public_live") {
    $publicLive = [bool]$data.public_live
}
if ($data.PSObject.Properties.Name -contains "public_hls") {
    $publicHls = [bool]$data.public_hls
}

$tickerEnabled = $false
$tickerText = ""
$tickerSpeed = 32
$tickerFontSize = 14
$tickerHeight = 40
$tickerBackground = ""
$tickerSeparator = ""
$tickerItems = @()
if ($data.PSObject.Properties.Name -contains "ticker" -and $data.ticker) {
    $ticker = $data.ticker
    if ($ticker.PSObject.Properties.Name -contains "enabled") {
        $tickerEnabled = [bool]$ticker.enabled
    }
    if ($ticker.PSObject.Properties.Name -contains "text") {
        $tickerText = [string]$ticker.text
    }
    if ($ticker.PSObject.Properties.Name -contains "speed") {
        try {
            $tickerSpeed = [int][double]$ticker.speed
        } catch {
            $tickerSpeed = 32
        }
    }
    if ($ticker.PSObject.Properties.Name -contains "font_size") {
        try {
            $tickerFontSize = [int][double]$ticker.font_size
        } catch {
            $tickerFontSize = 14
        }
    }
    if ($ticker.PSObject.Properties.Name -contains "height") {
        try {
            $tickerHeight = [int][double]$ticker.height
        } catch {
            $tickerHeight = 40
        }
    }
    if ($ticker.PSObject.Properties.Name -contains "background") {
        $tickerBackground = [string]$ticker.background
    }
    if ($ticker.PSObject.Properties.Name -contains "separator") {
        $tickerSeparator = [string]$ticker.separator
    }
    if ($ticker.PSObject.Properties.Name -contains "items") {
        $rawItems = $ticker.items
        if ($rawItems -is [System.Collections.IEnumerable] -and $rawItems -isnot [string]) {
            foreach ($item in $rawItems) {
                if (-not $item) { continue }
                $itemText = ""
                if ($item.PSObject.Properties.Name -contains "text") {
                    $itemText = [string]$item.text
                }
                $itemText = ($itemText -replace "`r|`n", " ").Trim()
                $itemHtml = ""
                if ($item.PSObject.Properties.Name -contains "html") {
                    $itemHtml = [string]$item.html
                }
                $itemHtml = $itemHtml.Trim()
                if (-not $itemText -and $itemHtml) {
                    $itemText = ($itemHtml -replace "<[^>]+>", " ")
                    $itemText = ($itemText -replace "\s+", " ").Trim()
                }
                if (-not $itemText -and -not $itemHtml) { continue }
                $entry = [ordered]@{
                    text = $itemText
                    bold = [bool]$item.bold
                }
                if ($itemHtml) {
                    $entry.html = $itemHtml
                }
                if ($item.PSObject.Properties.Name -contains "id") {
                    $itemId = [string]$item.id
                    if ($itemId.Trim()) {
                        $entry.id = $itemId.Trim()
                    }
                }
                $tickerItems += $entry
            }
        }
    }
}
$tickerText = ($tickerText -replace "`r|`n", " ").Trim()
if ($tickerSpeed -lt 10) { $tickerSpeed = 10 }
if ($tickerSpeed -gt 120) { $tickerSpeed = 120 }
if ($tickerFontSize -lt 10) { $tickerFontSize = 10 }
if ($tickerFontSize -gt 28) { $tickerFontSize = 28 }
if ($tickerHeight -lt 28) { $tickerHeight = 28 }
if ($tickerHeight -gt 80) { $tickerHeight = 80 }
$tickerBackground = $tickerBackground.Trim()
if ($tickerBackground -notmatch "^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$") {
    $tickerBackground = ""
}
$tickerSeparator = ($tickerSeparator -replace "`r|`n", " ").Trim()
if ($tickerSeparator.Length -gt 6) {
    $tickerSeparator = $tickerSeparator.Substring(0, 6).Trim()
}
if (-not $tickerSeparator) {
    $tickerSeparator = "•"
}
if ($tickerItems.Count -eq 0 -and $tickerText) {
    $tickerItems = @([ordered]@{ text = $tickerText; bold = $false })
}
$legacyText = ""
if ($tickerItems.Count -gt 0) {
    $legacyText = ($tickerItems | ForEach-Object { $_.text }) -join (" " + $tickerSeparator + " ")
}
if (-not $legacyText) {
    $legacyText = $tickerText
}
$legacyText = ($legacyText -replace "`r|`n", " ").Trim()

$timestamp = [DateTimeOffset]::UtcNow
$publicPayload = [ordered]@{
    public_live = $publicLive
    public_hls = $publicHls
    ticker = [ordered]@{
        enabled = $tickerEnabled
        speed = $tickerSpeed
        font_size = $tickerFontSize
        height = $tickerHeight
        background = $tickerBackground
        separator = $tickerSeparator
        items = $tickerItems
        text = $legacyText
    }
    updated_at_epoch = [int]$timestamp.ToUnixTimeSeconds()
    updated_at = $timestamp.ToString("o")
}
$publicPayload | ConvertTo-Json -Compress | Out-File -FilePath $publicConfigFile -Encoding ASCII -Force
("set `$public_hls " + ($(if ($publicHls) { "1" } else { "0" })) + ";") | Out-File -FilePath $publicHlsConf -Encoding ASCII -Force

$confAfter = Get-Content $confFile -Raw
$publicHlsAfter = Get-Content $publicHlsConf -Raw
$confChanged = $confBefore -ne $confAfter
$publicHlsChanged = $publicHlsBefore -ne $publicHlsAfter
$needsReload = $restart -or $confChanged -or $publicHlsChanged

if (!(Test-Path $nginxExe)) {
    Write-Error "nginx.exe not found in repo root."
    exit 1
}

if (-not $needsReload) {
    exit 0
}

& $nginxExe -p $Root -c conf\nginx.local.conf -t | Out-Null

try {
    if ($restart) {
        & $nginxExe -p $Root -c conf\nginx.local.conf -s stop | Out-Null
        Start-Process -FilePath $nginxExe -ArgumentList "-p `"$Root`" -c conf\nginx.local.conf" -WorkingDirectory $Root | Out-Null
    } else {
        & $nginxExe -p $Root -c conf\nginx.local.conf -s reload | Out-Null
    }
} catch {
    if (-not $restart) {
        & $nginxExe -p $Root -c conf\nginx.local.conf -s stop | Out-Null
        Start-Process -FilePath $nginxExe -ArgumentList "-p `"$Root`" -c conf\nginx.local.conf" -WorkingDirectory $Root | Out-Null
    } else {
        throw
    }
}
