#!/usr/bin/env python3
import json
import os
import sys
from pathlib import Path
from typing import Optional, Tuple
from urllib.parse import urlsplit


def clean(value: str) -> str:
    if value is None:
        return ""
    value = value.strip()
    if any(ch in value for ch in ["\n", "\r", ";"]):
        raise ValueError("Invalid characters in value")
    return value


def build_push_url(base: str, key: str) -> Optional[str]:
    if not base:
        return None
    if key:
        if base.endswith("/"):
            return base + key.lstrip("/")
        return base + "/" + key.lstrip("/")
    return base


def normalize_path(path: str) -> str:
    if not path:
        return "/"
    if not path.startswith("/"):
        return "/" + path
    return path


def parse_rtmps(base: str) -> Optional[Tuple[str, int, str]]:
    parts = urlsplit(base)
    if parts.scheme.lower() != "rtmps":
        return None
    host = parts.hostname
    if not host:
        return None
    port = parts.port or 443
    path = normalize_path(parts.path)
    return host, port, path


def main() -> int:
    if len(sys.argv) not in (3, 4):
        print("Usage: restream-generate.py <restream.json> <output.conf> [stunnel.conf]")
        return 2
    src = Path(sys.argv[1])
    out = Path(sys.argv[2])
    stunnel_out = Path(sys.argv[3]) if len(sys.argv) == 4 else None

    data = json.loads(src.read_text(encoding="utf-8"))
    destinations = data.get("destinations", [])

    tunnel_base_port = int(os.environ.get("RTMPS_TUNNEL_BASE_PORT", "19350"))
    tunnel_port = tunnel_base_port
    stunnel_sections = []

    lines = [
        "# Auto-generated by restream-generate.py",
        "# Do not edit manually. Edit data/restream.json instead.",
    ]

    for index, dest in enumerate(destinations, start=1):
        if not dest.get("enabled", False):
            continue
        try:
            base = clean(dest.get("rtmp_url", ""))
            key = clean(dest.get("stream_key", ""))
        except ValueError:
            continue
        if not base:
            continue
        parsed = parse_rtmps(base)
        if parsed:
            host, port, path = parsed
            local_port = tunnel_port
            tunnel_port += 1
            base = f"rtmp://127.0.0.1:{local_port}{path}"
            name = dest.get("id") or dest.get("name") or f"dest-{index}"
            safe_name = "".join(ch if ch.isalnum() or ch in "-_" else "-" for ch in name)
            section_name = f"rtmps-{safe_name}-{local_port}"
            stunnel_sections.append(
                [
                    f"[{section_name}]",
                    "client = yes",
                    f"accept = 127.0.0.1:{local_port}",
                    f"connect = {host}:{port}",
                    f"sni = {host}",
                    "",
                ]
            )
        push_url = build_push_url(base, key)
        if not push_url:
            continue
        lines.append(f"push {push_url};")

    out.write_text("\n".join(lines) + "\n", encoding="utf-8")

    if stunnel_out is not None:
        stunnel_lines = [
            "# Auto-generated by restream-generate.py",
            "# Do not edit manually. Edit data/restream.json instead.",
        ]
        for section in stunnel_sections:
            stunnel_lines.extend(section)
        stunnel_out.write_text("\n".join(stunnel_lines).rstrip() + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
