#!/usr/bin/env python3
import json
import sys
from pathlib import Path
from typing import Optional


def clean(value: str) -> str:
    if value is None:
        return ""
    value = value.strip()
    if any(ch in value for ch in ["\n", "\r", ";"]):
        raise ValueError("Invalid characters in value")
    return value


def build_push_url(dest: dict) -> Optional[str]:
    base = clean(dest.get("rtmp_url", ""))
    key = clean(dest.get("stream_key", ""))
    if not base:
        return None
    if key:
        if base.endswith("/"):
            return base + key.lstrip("/")
        return base + "/" + key.lstrip("/")
    return base


def main() -> int:
    if len(sys.argv) != 3:
        print("Usage: restream-generate.py <restream.json> <output.conf>")
        return 2
    src = Path(sys.argv[1])
    out = Path(sys.argv[2])
    data = json.loads(src.read_text(encoding="utf-8"))
    destinations = data.get("destinations", [])

    lines = [
        "# Auto-generated by restream-generate.py",
        "# Do not edit manually. Edit data/restream.json instead.",
    ]

    for dest in destinations:
        if not dest.get("enabled", False):
            continue
        try:
            push_url = build_push_url(dest)
        except ValueError:
            continue
        if not push_url:
            continue
        lines.append(f"push {push_url};")

    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
