param()

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$dataDir = Join-Path $Root "data"
$jsonFile = Join-Path $dataDir "restream.json"
$confFile = Join-Path $dataDir "restream.conf"
$publicConfigFile = Join-Path $dataDir "public-config.json"
$publicHlsConf = Join-Path $dataDir "public-hls.conf"
$confCopy = Join-Path $Root "conf\data\restream.conf"
$defaultConfig = Join-Path $Root "config\restream.default.json"
$nginxExe = Join-Path $Root "nginx.exe"
$restart = ($env:RESTART_NGINX -eq "1")
$confBefore = if (Test-Path $confFile) { Get-Content $confFile -Raw } else { "" }
$publicHlsBefore = if (Test-Path $publicHlsConf) { Get-Content $publicHlsConf -Raw } else { "" }

function Clean-Value {
    param([string]$Value)
    if ($null -eq $Value) { return "" }
    $trimmed = $Value.Trim()
    if ($trimmed -match "[\r\n;]") { return $null }
    return $trimmed
}

function Build-PushUrl {
    param($Dest)
    $base = Clean-Value $Dest.rtmp_url
    if ($null -eq $base -or $base -eq "") { return $null }
    $key = Clean-Value $Dest.stream_key
    if ($null -eq $key) { return $null }
    if ($key) {
        $cleanKey = $key.TrimStart("/")
        if ($base.EndsWith("/")) { return $base + $cleanKey }
        return $base + "/" + $cleanKey
    }
    return $base
}

New-Item -ItemType Directory -Force -Path $dataDir | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $Root "conf\data") | Out-Null

if (!(Test-Path $jsonFile)) {
    Copy-Item $defaultConfig $jsonFile -Force
}

$data = Get-Content $jsonFile -Raw | ConvertFrom-Json
$lines = @(
    "# Auto-generated by restream-apply.ps1",
    "# Do not edit manually. Edit data/restream.json instead."
)

if ($data -and $data.destinations) {
    foreach ($dest in $data.destinations) {
        if (-not $dest.enabled) { continue }
        $pushUrl = Build-PushUrl $dest
        if ($pushUrl) { $lines += ("push " + $pushUrl + ";") }
    }
}

$lines -join "`n" | Out-File -FilePath $confFile -Encoding ASCII -Force
Copy-Item $confFile $confCopy -Force

$publicLive = $true
$publicHls = $true
if ($data.PSObject.Properties.Name -contains "public_live") {
    $publicLive = [bool]$data.public_live
}
if ($data.PSObject.Properties.Name -contains "public_hls") {
    $publicHls = [bool]$data.public_hls
}
$timestamp = [DateTimeOffset]::UtcNow
$publicPayload = [ordered]@{
    public_live = $publicLive
    public_hls = $publicHls
    updated_at_epoch = [int]$timestamp.ToUnixTimeSeconds()
    updated_at = $timestamp.ToString("o")
}
$publicPayload | ConvertTo-Json -Compress | Out-File -FilePath $publicConfigFile -Encoding ASCII -Force
("set `$public_hls " + ($(if ($publicHls) { "1" } else { "0" })) + ";") | Out-File -FilePath $publicHlsConf -Encoding ASCII -Force

$confAfter = Get-Content $confFile -Raw
$publicHlsAfter = Get-Content $publicHlsConf -Raw
$confChanged = $confBefore -ne $confAfter
$publicHlsChanged = $publicHlsBefore -ne $publicHlsAfter
$needsReload = $restart -or $confChanged -or $publicHlsChanged

if (!(Test-Path $nginxExe)) {
    Write-Error "nginx.exe not found in repo root."
    exit 1
}

if (-not $needsReload) {
    exit 0
}

& $nginxExe -p $Root -c conf\nginx.local.conf -t | Out-Null

try {
    if ($restart) {
        & $nginxExe -p $Root -c conf\nginx.local.conf -s stop | Out-Null
        Start-Process -FilePath $nginxExe -ArgumentList "-p `"$Root`" -c conf\nginx.local.conf" -WorkingDirectory $Root | Out-Null
    } else {
        & $nginxExe -p $Root -c conf\nginx.local.conf -s reload | Out-Null
    }
} catch {
    if (-not $restart) {
        & $nginxExe -p $Root -c conf\nginx.local.conf -s stop | Out-Null
        Start-Process -FilePath $nginxExe -ArgumentList "-p `"$Root`" -c conf\nginx.local.conf" -WorkingDirectory $Root | Out-Null
    } else {
        throw
    }
}
