param()

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$dataDir = Join-Path $Root "data"
$jsonFile = Join-Path $dataDir "restream.json"
$confFile = Join-Path $dataDir "restream.conf"
$confCopy = Join-Path $Root "conf\data\restream.conf"
$defaultConfig = Join-Path $Root "config\restream.default.json"
$nginxExe = Join-Path $Root "nginx.exe"
$restart = ($env:RESTART_NGINX -eq "1")

function Clean-Value {
    param([string]$Value)
    if ($null -eq $Value) { return "" }
    $trimmed = $Value.Trim()
    if ($trimmed -match "[\r\n;]") { return $null }
    return $trimmed
}

function Build-PushUrl {
    param($Dest)
    $base = Clean-Value $Dest.rtmp_url
    if ($null -eq $base -or $base -eq "") { return $null }
    $key = Clean-Value $Dest.stream_key
    if ($null -eq $key) { return $null }
    if ($key) {
        $cleanKey = $key.TrimStart("/")
        if ($base.EndsWith("/")) { return $base + $cleanKey }
        return $base + "/" + $cleanKey
    }
    return $base
}

New-Item -ItemType Directory -Force -Path $dataDir | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $Root "conf\data") | Out-Null

if (!(Test-Path $jsonFile)) {
    Copy-Item $defaultConfig $jsonFile -Force
}

$data = Get-Content $jsonFile -Raw | ConvertFrom-Json
$lines = @(
    "# Auto-generated by restream-apply.ps1",
    "# Do not edit manually. Edit data/restream.json instead."
)

if ($data -and $data.destinations) {
    foreach ($dest in $data.destinations) {
        if (-not $dest.enabled) { continue }
        $pushUrl = Build-PushUrl $dest
        if ($pushUrl) { $lines += ("push " + $pushUrl + ";") }
    }
}

$lines -join "`n" | Out-File -FilePath $confFile -Encoding ASCII -Force
Copy-Item $confFile $confCopy -Force

if (!(Test-Path $nginxExe)) {
    Write-Error "nginx.exe not found in repo root."
    exit 1
}

& $nginxExe -p $Root -c conf\nginx.local.conf -t | Out-Null

try {
    if ($restart) {
        & $nginxExe -p $Root -c conf\nginx.local.conf -s stop | Out-Null
        Start-Process -FilePath $nginxExe -ArgumentList "-p `"$Root`" -c conf\nginx.local.conf" -WorkingDirectory $Root | Out-Null
    } else {
        & $nginxExe -p $Root -c conf\nginx.local.conf -s reload | Out-Null
    }
} catch {
    if (-not $restart) {
        & $nginxExe -p $Root -c conf\nginx.local.conf -s stop | Out-Null
        Start-Process -FilePath $nginxExe -ArgumentList "-p `"$Root`" -c conf\nginx.local.conf" -WorkingDirectory $Root | Out-Null
    } else {
        throw
    }
}
